### ISSUE TITLE
Badge Is not working in android

### ISSUE THREAD

**Issue by maniacube** [xabre/xamarin-forms-tab-badge#13] opened 2017-03-30 05:45 UTC
Hi, 

I have downloaded the sample project which is available in "https://github.com/xabre/xamarin-forms-tab-badge". Then when i tried to run that app in iOS device, it is working fine. But in android, i am getting crash with out any reason. Can you guys please help us to resolve the issue and it should work perfectly in android devices too.

Thanks & Regards,
Manigandan V.

**Comment by xabre** [comment] 2017-03-30 22:10
I need more info. Please copy paste the application output or logcat output so that we can see a stacktrace.

**Comment by maniacube** [comment] 2017-04-03 11:54
@xabre,

              I am not getting any error message in logcat. i am getting crash only. And i didnt do anything extra work in the downloaded project. What ever the sample project available in the "https://github.com/xabre/xamarin-forms-tab-badge" link, i just downloaded and tried to run the app in android. I am not even able to see the initial screen itself.

**Comment by xabre** [comment] 2017-04-07 11:10
Did you check your Xamarin update status and Android SDK status? Make sure everything is up to date. (i.e. build tools, sdk etc)

**Comment by xabre** [comment] 2017-06-27 15:13
Fixed with 1.0.2. Guessing was a duplicate of #15

**Closed by xabre** 2017-06-27 15:13 UTC

**Comment by sumitsisodia007** [comment] 2017-08-29 11:44
Hi,
i have downl;oad version 
I have downloaded the sample project which is available in "https://github.com/xabre/xamarin-forms-tab-badge". in android, i am getting Badge any tabes . Can you guys please help us to resolve the issue .
I have to try 1.0.2 version and already update xamarin.Form 2.3.4.247. but badge is not showing .

Thanks & Regards,
