### ISSUE TITLE
Not Showing Badge icon ,Badge Color and Badge Text

### ISSUE THREAD

**Issue by sumitsisodia007** [xabre/xamarin-forms-tab-badge#35] opened 2017-08-30 05:11 UTC
Hi,
I am using VS-2017 and update Xamarin Form Latest version.
i am using badge plugins 1.3.0 pre or 1.1.3  but not showing badge icon ,text and color.
what should i do any body can help me .
![screenshot_1504069434](https://user-images.githubusercontent.com/30065887/29856348-d9be22e6-8d6f-11e7-80cd-a5ece076075e.png)

Thanks for advance .

**Comment by benevbright** [comment] 2017-09-20 08:01
Same here, I have no idea when it stopped working?! 
I just noticed somehow that the badge is not showing. 

Tested on Android. 
XF ver : 2.3.4.270 stable
badge plugin : 1.1.3
tested device : Samsung Galaxy S4 - Android 5.0.1
Android SDK : 7.1(API 25)


Can we expect quick fix for this? 
Thanks.

**Comment by xabre** [comment] 2017-09-22 06:55
I would fix it asap but, unfortunately I'm not able to reproduce it on my device/emulator.... Do you get any errors in your output/logcat?

**Comment by benevbright** [comment] 2017-09-23 08:21
Hi Adrian, 

Yes. You are right. 
I downloaded the sample and tested it after I updated all packages as I said above. 
It turns out it works fine. 

I should check again what did I mistake. 
I'm sorry about it and thanks.

**Comment by benevbright** [comment] 2017-09-23 09:16
> Caution - Custom TabbedPage / Custom Renderers

>If you are using a custom renderer for TabbedPage please change it to inherit from BadgedTabbedPageRenderer and you are all set. Of course dont forget to register your own renderer.

Hi, I found my mistake. 
I don't know since when my code has changed, but my TabbedPageRenderer didn't inherit from BadgedTabbedPageRenderer.

I changed it and the problem is gone.

I'm sorry.

**Comment by xabre** [comment] 2017-09-24 14:38
I'm going to close this issue for now. Feel free to repopen it if you find a bug.

**Closed by xabre** 2017-09-24 14:38 UTC
Labels: need more info

**Comment by kamranmasud** [comment] 2020-07-08 09:43
> I would fix it asap but, unfortunately I'm not able to reproduce it on my device/emulator.... Do you get any errors in your output/logcat?

I want to show badge on cart tab..on the other side i want to show root page on tab clicked or reselected..I am using your plugin to show badge on tab but when i use renderer to show root page on tab reselected then badge is not visible. I am finding the solution because i want both of these functionalities in my app..
I am using the following renderer to navigate to root page when i reselect tab:

[assembly: ExportRenderer(typeof(TabPage), typeof(MainPageRenderer))]
namespace MyProject.Droid.Renderers
{
public class MainPageRenderer : TabbedPageRenderer, TabLayout.IOnTabSelectedListener
{
private TabPage _page;
protected override void OnElementChanged(ElementChangedEventArgs e)
{
base.OnElementChanged(e);
if (e.NewElement != null)
{
_page = (TabPage)e.NewElement;
}
else
{
_page = (TabPage)e.OldElement;
}

    }
    async void TabLayout.IOnTabSelectedListener.OnTabReselected(TabLayout.Tab tab)
    {
        await _page.CurrentPage.Navigation.PopToRootAsync();
    }
}
}

When i comment this code then badge will visible otherwise not
